<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />



    <link name="base_link">
        <visual> <!-- 可视化部分 -->
            <geometry> <!-- 几何体 -->
                <box size="${base_length} ${base_width} ${base_height}"/> <!-- 长方形（长宽高）（单位m） -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <!-- 这个origin其实是物体的中心相较于物体的坐标系的位置，也就是物体坐标系-》物体中心，
            注意的是默认初始情况下物体的坐标系就在物体的中心 -->
            <material name="blue"/>
        </visual>

        <collision> <!-- 碰撞设置 (可以发现碰撞设置跟可视化设置基本差不多)-->
            <geometry> <!-- 几何体 -->
                <box size="${base_length} ${base_width} ${base_height}"/> <!-- 长方形（长宽高）（单位m） -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>

        <!-- 转动惯量设置 -->
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>

            <collision> <!-- 对于圆柱体来说，碰撞设置最好设置成球体！ -->
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                    o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left"  />


    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" 
                              o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="base_footlink">
    </link>


    <joint name="base_joint" type="fixed">
        <parent link="base_footlink" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-base_width / 2.0 + -wheel_length / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${base_width / 2.0 + wheel_length / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>
    
</robot>